module.exports = {
  up: function (queryInterface, Sequelize) {
    'use strict';
    return queryInterface.bulkInsert('adies', 
    [
      {
        "name":"Audrey Carlsen",
        "cohort":1,
        "github_username":"audreycarlsen",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/audrey-carlsen-96b29463",
        "image":"",
        "email":"foo1@bar.com",
        "companyId":3,
        "bio":"Audrey Carlsen was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Asha Golveo",
        "cohort":1,
        "github_username":"ashag",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/ashagolveo",
        "image":"",
        "email":"agolveo@gmail.com",
        "companyId":2,
        "bio":"Asha Golveo was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Shadae Holmes",
        "cohort":1,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/shadae",
        "image":"",
        "email":"shadaeholmes@gmail.com",
        "companyId":11,
        "bio":"Shadae Holmes was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Hsing-Hui Hsu",
        "cohort":1,
        "github_username":"Elffers",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/hhhsu",
        "image":"",
        "email":"hhhsu1@gmail.com",
        "companyId":7,
        "bio":"Hsing-Hui Hsu was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Blake Johnson",
        "cohort":1,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/blake-johnson-15801937",
        "image":"",
        "email":"foo2@bar.com",
        "companyId":4,
        "bio":"Blake Johnson was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Anne Kimsey",
        "cohort":1,
        "github_username":"AKimZ",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/askimsey",
        "image":"",
        "email":"foo3@bar.com",
        "companyId":1,
        "bio":"Anne Kimsey was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Whitney-Rose Levis",
        "cohort":1,
        "github_username":"roseaboveit",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/whitneylevis",
        "image":"",
        "email":"ms.whitney.levis@gmail.com",
        "companyId":13,
        "bio":"Whitney-Rose Levis was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Davida Marion",
        "cohort":1,
        "github_username":"Sgtpluck",
        "twitter":"@davidamarion",
        "linked_in_url":"https://www.linkedin.com/in/davidamarion",
        "image":"",
        "email":"davidamarion@gmail.com",
        "companyId":6,
        "bio":"Davida Marion was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Melinda Mizuta",
        "cohort":1,
        "github_username":"mkmizuta",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/melinda-mizuta-3655b57",
        "image":"",
        "email":"foo4@bar.com",
        "companyId":1,
        "bio":"Melinda Mizuta was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Liz Rush",
        "cohort":1,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lizrush",
        "image":"",
        "email":"liz@lizmrush.com",
        "companyId":10,
        "bio":"Liz Rush was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Christina Thompson",
        "cohort":1,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/thompsonchristina",
        "image":"",
        "email":"c.thompsonms@gmail.com",
        "companyId":5,
        "bio":"Christina Thompson was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Elizabeth Uselton",
        "cohort":1,
        "github_username":"ElizabethU",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/elizabeth-uselton-17a3994a",
        "image":"",
        "email":"foo5@bar.com",
        "companyId":7,
        "bio":"Elizabeth Uselton was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Sue White",
        "cohort":1,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/sue-white-b8953186",
        "image":"",
        "email":"sue@mailworks.org",
        "companyId":12,
        "bio":"Sue White was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Ellen Wondra-Lindley",
        "cohort":1,
        "github_username":"shanghaiellen",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/ellen-wondra-lindley-27359977",
        "image":"",
        "email":"foo6@bar.com",
        "companyId":8,
        "bio":"Ellen Wondra-Lindley was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Galina Yermicheva",
        "cohort":1,
        "github_username":"gyermich",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/galina-yermicheva-68518196",
        "image":"",
        "email":"foo7@bar.com",
        "companyId":9,
        "bio":"Galina Yermicheva was a student in Ada Developers Academy cohort 1. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Rachel Adler",
        "cohort":2,
        "github_username":"",
        "twitter":"@rsmomo",
        "linked_in_url":"https://www.linkedin.com/in/rmoshier",
        "image":"Rachel.JPG",
        "email":"rmoshier@gmail.com",
        "companyId":6,
        "bio":"Rachel Adler was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Richa Arora",
        "cohort":2,
        "github_username":"ricarora",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/richa-arora-4985085b",
        "image":"richa.jpg",
        "email":"ricarora@gmail.com",
        "companyId":1,
        "bio":"Richa Arora was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Katie Bosch",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/katie-bosch-669782a5",
        "image":"Katie.JPG",
        "email":"kab761@gmail.com",
        "companyId":2,
        "bio":"Katie Bosch was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Linnea Damer",
        "cohort":2,
        "github_username":"lkdamer",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/linnea-damer-5897322b",
        "image":"Linnea.jpg",
        "email":"lkdamer@gmail.com",
        "companyId":7,
        "bio":"Linnea Damer was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Bri Dotson",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/bri-dotson-9b613774",
        "image":"bri.jpg",
        "email":"bridotson@gmail.com",
        "companyId":9,
        "bio":"Bri Dotson was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kate Fulton",
        "cohort":2,
        "github_username":"KF525",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/katefulton",
        "image":"Kat.JPG",
        "email":"katesuzannefulton@gmail.com",
        "companyId":4,
        "bio":"Kate Fulton was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kristina Hjertberg",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/khjrtbrg",
        "image":"",
        "email":"hjert.k@gmail.com",
        "companyId":10,
        "bio":"Kristina Hjertberg was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kamilah Jenkins",
        "cohort":2,
        "github_username":"kamilahjae",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kamilah-jenkins-b92a9974",
        "image":"Kamilah.jpeg",
        "email":"kamilah.jenkins@gmail.com",
        "companyId":7,
        "bio":"Kamilah Jenkins was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Rachelle Keblitis",
        "cohort":2,
        "github_username":"rkeblitis",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/rkeblitis",
        "image":"",
        "email":"rkeblitis@gmail.com",
        "companyId":16,
        "bio":"Rachelle Keblitis was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Stephanie Kwak",
        "cohort":2,
        "github_username":"skwak",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/stephaniekwak",
        "image":"Stephanie Pi.jpeg",
        "email":"eskay@ghadibalo.com",
        "companyId":17,
        "bio":"Stephanie Kwak was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Bonnie Kwong",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/bonnie-kwong-064398a",
        "image":"",
        "email":"kbonnie@gmail.com",
        "companyId":1,
        "bio":"Bonnie Kwong was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Holly Leary",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/holly-leary-63138766",
        "image":"holly-ada.jpg",
        "email":"schleary@gmail.com",
        "companyId":5,
        "bio":"Holly Leary was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Rebecca Mark",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/rebecca-mark-31253728",
        "image":"Rebecca Mark.jpg",
        "email":"rebecca.lmark@gmail.com",
        "companyId":4,
        "bio":"Rebecca Mark was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kristen McCabe",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kristen-mccabe-50119bb",
        "image":"",
        "email":"kmccabe3@gmail.com",
        "companyId":16,
        "bio":"Kristen McCabe was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Lily Pace",
        "cohort":2,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lily-pace-b1433140",
        "image":"Lily.jpg",
        "email":"lilyfpace@gmail.com",
        "companyId":18,
        "bio":"Lily Pace was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Calla Patel",
        "cohort":2,
        "github_username":"callapatel",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/callapatel",
        "image":"calla.jpeg",
        "email":"callapatel@gmail.com",
        "companyId":1,
        "bio":"Calla Patel was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Katherine Patke",
        "cohort":2,
        "github_username":"katke",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kpatke",
        "image":"katef.jpg",
        "email":"kmmpatke@gmail.com",
        "companyId":17,
        "bio":"Katherine Patke was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Crystal Perreira",
        "cohort":2,
        "github_username":"crystalperreira",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/crystalperreira",
        "image":"crystalperreira.jpg",
        "email":"cvperreira@gmail.com",
        "companyId":16,
        "bio":"Crystal Perreira was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Stephanie Pi",
        "cohort":2,
        "github_username":"piinthecloud",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/stephanie-pi-b446ab25",
        "image":"StephanieK.jpg",
        "email":"stephmpi@gmail.com",
        "companyId":16,
        "bio":"Stephanie Pi was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Brenda Praggastis",
        "cohort":2,
        "github_username":"bpraggastis",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/brenda-praggastis-2451919a",
        "image":"",
        "email":"bpraggastis@gmail.com",
        "companyId":14,
        "bio":"Brenda Praggastis was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Allie Sterling",
        "cohort":2,
        "github_username":"ahsterling",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/sterlingallison",
        "image":"Allie.jpg",
        "email":"sterling.allie@gmail.com",
        "companyId":12,
        "bio":"Allie Sterling was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Cate Uselton",
        "cohort":2,
        "github_username":"catstavi",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/cate-uselton-62a5bb61",
        "image":"",
        "email":"cathode.use@gmail.com",
        "companyId":15,
        "bio":"Cate Uselton was a student in Ada Developers Academy cohort 2. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Alice Rhomieux",
        "cohort":3,
        "github_username":"arhx",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/alicerhomieux",
        "image":"Alice1.jpg",
        "email":"alice.rhomieux@gmail.com",
        "companyId":16,
        "bio":"Alice Rhomieux was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Amira Hailemariam",
        "cohort":3,
        "github_username":"amirahaile",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/amirahaile",
        "image":"Amira1.jpg",
        "email":"AWatkins31@gmail.com",
        "companyId":20,
        "bio":"Amira Hailemariam was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Anita Wang",
        "cohort":3,
        "github_username":"acmei",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/acmwang",
        "image":"Anita2.jpg",
        "email":"michellemccarthy@hotmail.com",
        "companyId":27,
        "bio":"Anita Wang was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Ashley Watkins",
        "cohort":3,
        "github_username":"catchingash",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/catchingash",
        "image":"Ashley2.jpg",
        "email":"drvonnjerryxlii@gmail.com",
        "companyId":23,
        "bio":"Ashley Watkins was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Brandi Wilson",
        "cohort":3,
        "github_username":"QuartzBrandi",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/brandiewilson",
        "image":"Brandi2.jpg",
        "email":"camarleigh@gmail.com",
        "companyId":26,
        "bio":"Brandi Wilson was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Brenna Leker",
        "cohort":3,
        "github_username":"Brennaleker",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/brennaleker",
        "image":"Brenna2.jpg",
        "email":"loraine@lorainekv.com",
        "companyId":15,
        "bio":"Brenna Leker was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Brittany Walentin",
        "cohort":3,
        "github_username":"brittinator",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/brittany-walentin-b197234",
        "image":"Brittany2.jpg",
        "email":"elgrenier@gmail.com",
        "companyId":1,
        "bio":"Brittany Walentin was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Carly Jugler",
        "cohort":3,
        "github_username":"carjug",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/carly-jugler-800234b9",
        "image":"Carly2.jpg",
        "email":"asovay@gmail.com",
        "companyId":19,
        "bio":"Carly Jugler was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Corinne Pingul",
        "cohort":3,
        "github_username":"corinnepingul",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/corinnepingul",
        "image":"Corinne2.jpg",
        "email":"corinnepingul@gmail.com",
        "companyId":1,
        "bio":"Corinne Pingul was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Elia Grenier",
        "cohort":3,
        "github_username":"EliaMG",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/eliagrenier",
        "image":"Elia2.jpg",
        "email":"sallyamoore@gmail.com",
        "companyId":28,
        "bio":"Elia Grenier was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Elsa Moluf",
        "cohort":3,
        "github_username":"elsamoluf",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/elsamoluf",
        "image":"Elsa1.jpg",
        "email":"shannachau@gmail.com",
        "companyId":11,
        "bio":"Elsa Moluf was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Jeri Sommers",
        "cohort":3,
        "github_username":"drvonnjerryxlii",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/jerisommers",
        "image":"Jeri2.jpg",
        "email":"katrops@gmail.com",
        "companyId":25,
        "bio":"Jeri Sommers was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kari Lonczak",
        "cohort":3,
        "github_username":"lo-k",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kari-lonczak-83a1631b",
        "image":"Kari1.jpg",
        "email":"amira.dhaile@gmail.com",
        "companyId":16,
        "bio":"Kari Lonczak was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Katie Atrops",
        "cohort":3,
        "github_username":"ktrops",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/katie-atrops-73b61864",
        "image":"Katie1.jpg",
        "email":"brittany.walentin@gmail.com",
        "companyId":21,
        "bio":"Katie Atrops was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kyna Nguyen",
        "cohort":3,
        "github_username":"knguyen0710",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kyna-nguyen-61002378",
        "image":"Kyna2.jpg",
        "email":"wilson.e.brandi@gmail.com",
        "companyId":20,
        "bio":"Kyna Nguyen was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Lila Garcia",
        "cohort":3,
        "github_username":"lilagrc",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lilagarcia",
        "image":"Lila1.jpg",
        "email":"elsa.moluf@gmail.com",
        "companyId":22,
        "bio":"Lila Garcia was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Lindsey Reno",
        "cohort":3,
        "github_username":"lindseyreno",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lindsey-reno-23a2a0101",
        "image":"Lindsey1.jpg",
        "email":"lindseyannereno@gmail.com",
        "companyId":2,
        "bio":"Lindsey Reno was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Loraine Kanervisto",
        "cohort":3,
        "github_username":"lorainekv",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lorainekv",
        "image":"Loraine2.jpg",
        "email":"vikshab2010@hotmail.com",
        "companyId":29,
        "bio":"Loraine Kanervisto was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Marleigh Chiles",
        "cohort":3,
        "github_username":"camarleigh",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/camarleigh",
        "image":"Marleigh2.jpg",
        "email":"lilagrc@gmail.com",
        "companyId":25,
        "bio":"Marleigh Chiles was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Michelle McCarthy",
        "cohort":3,
        "github_username":"MisShellyMac",
        "twitter":"@MisShellyMac",
        "linked_in_url":"https://www.linkedin.com/in/michellejmccarthy",
        "image":"Michelle1.jpg",
        "email":"kari.lonczak@gmail.com",
        "companyId":24,
        "bio":"Michelle McCarthy was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Sally Moore",
        "cohort":3,
        "github_username":"sallyamoore",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/sally-a-moore-ph-d-05466719",
        "image":"Sally2.jpg",
        "email":"brennarama@gmail.com",
        "companyId":9,
        "bio":"Sally Moore was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Shanna Chau",
        "cohort":3,
        "github_username":"shannachau",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/shanna-chau-144aa474",
        "image":"Shanna1.jpg",
        "email":"carjug@gmail.com",
        "companyId":1,
        "bio":"Shanna Chau was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Viktoryia Shabunia",
        "cohort":3,
        "github_username":"vikshab",
        "twitter":"",
        "linked_in_url":"",
        "image":"Viktoryia1.jpg",
        "email":"khn710@gmail.com",
        "companyId":25,
        "bio":"Viktoryia Shabunia was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Wang (Loren) Wang",
        "cohort":3,
        "github_username":"wangg131",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/loren-wang-499aa46a",
        "image":"Wang1.jpg",
        "email":"wang131.131@gmail.com",
        "companyId":29,
        "bio":"Wang (Loren) Wang was a student in Ada Developers Academy cohort 3. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Risha Allen",
        "cohort":5,
        "github_username":"rishallen",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/risha-allen-ms-lmhc-00a87b18",
        "image":"Risha.JPG",
        "email":"risha.a@hotmail.com",
        "companyId":null,
        "bio":"Risha Allen was a student in Ada Developers Academy cohort 5. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Jennie Buechner",
        "cohort":4,
        "github_username":"jbuechs",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/jenniebuechner",
        "image":"Jennie.JPG",
        "email":"Janina.buechner@gmail.com",
        "companyId":30,
        "bio":"Jennie Buechner was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Audrey Davis",
        "cohort":4,
        "github_username":"Dreedle",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/audreylynndavis",
        "image":"Audrey.JPG",
        "email":"davis.audrey.lynn@gmail.com",
        "companyId":17,
        "bio":"Audrey Davis was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Katherine Defliese",
        "cohort":4,
        "github_username":"kdefliese",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/katherine-defliese-12284138",
        "image":"Katherine.JPG",
        "email":"kdefliese@gmail.com",
        "companyId":1,
        "bio":"Katherine Defliese was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Kelly Devlin",
        "cohort":4,
        "github_username":"Kedevlin",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/kellyerindevlin",
        "image":"Kelly.JPG",
        "email":"kelly_devlin@alumni.brown.edu",
        "companyId":16,
        "bio":"Kelly Devlin was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Daphne Gold",
        "cohort":4,
        "github_username":"daphnegold",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/daphnegold",
        "image":"Daphne.JPG",
        "email":"dg1181@nyu.edu",
        "companyId":16,
        "bio":"Daphne Gold was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Emily Gordon",
        "cohort":4,
        "github_username":"emgord",
        "twitter":"",
        "linked_in_url":"",
        "image":"Emily.JPG",
        "email":"emgord@gmail.com",
        "companyId":26,
        "bio":"Emily Gordon was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Lauren Granger",
        "cohort":4,
        "github_username":"lgranger",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/lrgranger",
        "image":"Lauren.JPG",
        "email":"Lr.granger21@gmail.com",
        "companyId":32,
        "bio":"Lauren Granger was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Annalee Herrera",
        "cohort":4,
        "github_username":"annaleeherrera",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/annalee-herrera-821aba14",
        "image":"Annalee.JPG",
        "email":"annaleeherrera@gmail.com",
        "companyId":33,
        "bio":"Annalee Herrera was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Tamar Hershenbaum",
        "cohort":4,
        "github_username":"TamarHershi",
        "twitter":"",
        "linked_in_url":"",
        "image":"Tamar.JPG",
        "email":"misstamar@gmail.com",
        "companyId":32,
        "bio":"Tamar Hershenbaum was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Ricky Hougland",
        "cohort":4,
        "github_username":"hougland",
        "twitter":"@houglande",
        "linked_in_url":"https://www.linkedin.com/in/ricky-hougland-368ab372",
        "image":"Ricky.JPG",
        "email":"houglande@gmail.com",
        "companyId":27,
        "bio":"Ricky Hougland was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Amy Hunter",
        "cohort":4,
        "github_username":"lacuchilla",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/amyrhunter",
        "image":"Amy.JPG",
        "email":"amyrhunter@gmail.com",
        "companyId":31,
        "bio":"Amy Hunter was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Sarah Kane",
        "cohort":5,
        "github_username":"",
        "twitter":"",
        "linked_in_url":"",
        "image":"SarahK.JPG",
        "email":"sarahkane682@yahoo.com",
        "companyId":null,
        "bio":"Sarah Kane was a student in Ada Developers Academy cohort 5. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Brittany Kohler",
        "cohort":4,
        "github_username":"brittanykohler",
        "twitter":"@B_rittK",
        "linked_in_url":"https://www.linkedin.com/in/brittanykohler",
        "image":"brittany_kohler.png",
        "email":"brittanykohler@gmail.com",
        "companyId":12,
        "bio":"Brittany Kohler was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Logan McDonald",
        "cohort":4,
        "github_username":"loganmeetsworld",
        "twitter":"@loganmeetsworld",
        "linked_in_url":"https://www.linkedin.com/in/mcdonaldlogan",
        "image":"Logan.JPG",
        "email":"loganmcdona11@gmail.com",
        "companyId":6,
        "bio":"Logan McDonald was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Jenna Nichols",
        "cohort":4,
        "github_username":"jennaplusplus",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/jenna-nichols-280a4816",
        "image":"Jenna.JPG",
        "email":"jennic@utexas.edu",
        "companyId":15,
        "bio":"Jenna Nichols was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Jessica Noglows",
        "cohort":4,
        "github_username":"noglows",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/jessicanoglows",
        "image":"Jessica.JPG",
        "email":"jessica.noglows@outlook.com",
        "companyId":14,
        "bio":"Jessica Noglows was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Desiree Poland",
        "cohort":4,
        "github_username":"desireepoland",
        "twitter":"",
        "linked_in_url":"",
        "image":"Desiree.JPG",
        "email":"desireepoland@gmail.com",
        "companyId":17,
        "bio":"Desiree Poland was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Meighan Rasley",
        "cohort":4,
        "github_username":"knaydee",
        "twitter":"",
        "linked_in_url":"",
        "image":"Meighan.JPG",
        "email":"meighanr@gmail.com",
        "companyId":7,
        "bio":"Meighan Rasley was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Claire Schechter",
        "cohort":4,
        "github_username":"CShekta",
        "twitter":"",
        "linked_in_url":"",
        "image":"Claire.JPG",
        "email":"ClaireS29@gmail.com",
        "companyId":2,
        "bio":"Claire Schechter was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Riley Spicer",
        "cohort":4,
        "github_username":"rileyrileyrose",
        "twitter":"@rileyrileyrose",
        "linked_in_url":"https://www.linkedin.com/in/rileyspicer",
        "image":"Riley.JPG",
        "email":"blankpagesandcoffeestains@gmail.com",
        "companyId":16,
        "bio":"Riley Spicer was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Rebecca Tolmach",
        "cohort":4,
        "github_username":"rmtolmach",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/rebecca-tolmach-7409a295",
        "image":"Rebecca.JPG",
        "email":"rmtolmach@gmail.com",
        "companyId":7,
        "bio":"Rebecca Tolmach was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Sarah Trowbridge",
        "cohort":4,
        "github_username":"trowbrsa",
        "twitter":"",
        "linked_in_url":"https://www.linkedin.com/in/sarahatrowbridge",
        "image":"SarahT.JPG",
        "email":"trowbrsa@gmail.com",
        "companyId":9,
        "bio":"Sarah Trowbridge was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      },
      {
        "name":"Hailey Willis",
        "cohort":4,
        "github_username":"wesleywillis",
        "twitter":"@weswilliscodes",
        "linked_in_url":"",
        "image":"Hailey.JPG",
        "email":"haileyw@gmail.com",
        "companyId":1,
        "bio":"Hailey Willis was a student in Ada Developers Academy cohort 4. She is now has a job doing some sort of programming and is doing amazing things.",
        "createdAt":new Date(),
        "updatedAt":new Date()
      }
    ], {});
  },

  down: function (queryInterface, Sequelize) {
    'use strict';
    return queryInterface.bulkDelete('adies', null, {});
  }
};
